### ISSUE TITLE
Mapas - Clientes - Error

### ISSUE THREAD

**Issue by hrprolluxer** [hrprolluxer/prosales#12]
No me salen las opciones de direcciones que trae el google maps y marca un error en la consola
adjunto imagen del error

![screen shot 2015-07-01 at 2 36 32 pm](https://cloud.githubusercontent.com/assets/12114054/8463301/d7ddb6ca-1ffe-11e5-9518-6d17bb550145.png)

**Comment by azprolluxer** [comment]
fixed!! ;D
