### ISSUE TITLE
Agregar botón "editar" al cliente

### ISSUE THREAD

**Issue by hrprolluxer** [hrprolluxer/prosales#14]
@azprolluxer , en la pantalla de ver cliente agregar el botón editar y que te mande a la pantalla editar

**Comment by azprolluxer** [comment]
listo! checa el color del botón, a mí me convenció, se ve bine ;D que opinas¿

**Comment by hrprolluxer** [comment]
El botón quedo muy bien, y el lugar también ahí debería ir good :+1:  :v:
