### ISSUE TITLE
Acomodar blocks y  columnas - Vista del cliente

### ISSUE THREAD

**Issue by hrprolluxer** [hrprolluxer/prosales#15]
Establecer el tamaño mínimo al cual pueden seguir siendo columnas los blocks y no se conviertan en rows inmediatamente al hacer resize de la pantalla

Aquí te vas a encontrar la documentación
http://getbootstrap.com/css/#grid

Los media queries que tu te avientas a mano, en bootstrap están en automático con el "col- "  mas los parámetros que acá abajo en el link te mencionan
  http://getbootstrap.com/css/#grid-options  <---ESTE IMPORTANTE

Así debería funcionar como la siguiente imagen
Mientras la pantalla sea (LG) (MD)  no deben ser rows
Los blocks no se no se deben convertir en rows solo hasta que la pantalla sea extra small (XS) y small (SM)
<img width="1419" alt="screen shot 2015-07-09 at 23 09 17" src="https://cloud.githubusercontent.com/assets/12114054/8612025/97224af0-268f-11e5-859d-3a0fc6527194.png">

Así esta el tuyo ves que con el mismo tamaño de la pantalla tus blocks en lugar de ser columnas son rows?
<img width="1411" alt="screen shot 2015-07-09 at 23 10 41" src="https://cloud.githubusercontent.com/assets/12114054/8612045/d78d8d5c-268f-11e5-98a3-188b501003a0.png">

**Comment by azprolluxer** [comment]
listo! ya se ve igual que la de orders ;)

**Comment by hrprolluxer** [comment]
@azprolluxer 

Así no es
Quitaste  class="col-lg-4"
y agregaste  class="col-md-4"

Acá viene,  http://getbootstrap.com/css/#grid-options 

hay que ponerle todos los casos  ( lg, md, sm, y xs ), lo dejaste solo con el md, y cuando la pantalla es sm (Small devices Tablets (≥768px)) se hacen rows y eso no se ve bien 
Como te decía arriba, la regla es hacer rows solo cuando sea xs...

revisa esa de Orders->pos, la imagen que te adjunte arriba

**Comment by azprolluxer** [comment]
ya quedó! no te habia entendido! jeje pero ya solo se hacen rows cuando el caso es xs.
