### ISSUE TITLE
Accounts - Address

### ISSUE THREAD

**Issue by hrprolluxer** [hrprolluxer/prosales#21]
•	Add address – when I click on search to look for the address on google maps I’m getting the following error:
{
   "error_message" : "This API project was not found. This API project may have been \"\n             R\"(deleted.",
   "results" : [],
   "status" : "REQUEST_DENIED"
}

Add address – when I click save I get a successful message but the browser’s vertical scrollbar (chrome) dissapears and a blackbar shows instead which does not allows me to scroll. I need to refresh the screen

Add address – When I select both shipping and billing address checkboxes, the system only adds the billing one

**Comment by azprolluxer** [comment]
All fixed!

**Comment by azprolluxer** [comment]
All fixed!
